spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3307/project
spring.datasource.username=root
spring.datasource.password=system

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.mail.host=smtp.gmail.com
spring.mail.username=omkarkadam7764@gmail.com
spring.mail.password=your app password
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

stripe.secret.key=strats with sk_